w7d3/MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index]
end

w7d3/MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :live, :studio, presence: true 
  
  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band
    
end

w7d3/MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album,
    dependent: :destroy
end

w7d3/MusicApp/app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
    attr_reader :password

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true 

    after_initialize :ensure_session_token

    # S
    # P
    # I
    # R +
    # E +

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(pw)
        BCrypt::Password.new(self.password_digest).is_password?(pw)
    end

    def self.find_by_credentials(email, pw)
        user = User.find_by(email: email)
        user && user.is_password?(pw) ? user : nil
    end
end

w7d3/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      render :show
    else
      redirect_to bands_url
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end
  
  private
  def album_params
    params.require(:album).permit(:title, :year, :live, :studio, :band_id)
  end

end

w7d3/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user.session_token
  end

end

w7d3/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.find_by(id: params[:id])

    if @band
      render :show
    else
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end
  
  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w7d3/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:email], params[:user][:password])

        if @user
            log_in_user!(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def destroy
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
    end
end

w7d3/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            log_in_user!(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :session_token)
    end

end

w7d3/MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

w7d3/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' 
    name='authenticity_token' 
    value='#{form_authenticity_token}'/>".html_safe
  end
end

w7d3/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

w7d3/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

w7d3/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

w7d3/MusicApp/app/views/bands/edit.html.erb
<h1>Edit a band</h1>

<form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <p>Your current band name is <%= @band.name %></p>
  <label for="band_name">Name:</label>
  <input type="text" id="band_name" name="band[name]" >
  <input type="submit" value="Edit Band">
</form>
<br>
<form action="<%= band_url(@band) %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Band">
</form>

w7d3/MusicApp/app/views/bands/index.html.erb
<h1>All Bands!</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
 </ul>
<br>
<a href="<%= new_band_url %>">Add a band</a>

w7d3/MusicApp/app/views/bands/new.html.erb
<h1>Add a band</h1>

<form action="<%= bands_url %>" method="POST">
  <%= auth_token %>
  <label for="band_name">Name:</label>
  <input type="text" id="band_name" name="band[name]">
  <input type="submit" value="Create Band">
</form>

w7d3/MusicApp/app/views/bands/show.html.erb
<a href="<%= bands_url %>">Home</a>
<h1><%= @band.name%> </h1>
<a href="<%= edit_band_url %>">Edit Band</a>

w7d3/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
        <input type="submit" value="Sign out">
      </form>
    <% else %>
      <form action="<%= new_user_url %>" method="GET">
        <input type="submit" value="Sign Up">
      </form>
      <form action="<%= new_session_url %>" method="GET">
        <input type="submit" value="Sign In">
      </form>
    <% end %>
    </header>

    <%= yield %>
  </body>
</html>

w7d3/MusicApp/app/views/users/new.html.erb
<h1>SIGN-UP</h1>

<form action="/users" method="POST">
  <%= auth_token %>


  <label for="user_email">Email:</label>
  <input type="text" id="user_email" name="user[email]" value="<%= @user.email %>">
  <br>
  <label for="user_password">Password:</label>
  <input type="password" id="user_password" name="user[password]">
  <br>
  <input type="submit" value="Sign Up">
</form>

w7d3/MusicApp/app/views/users/show.html.erb
<h1>Welcome, <%= @user.email %></h1>